### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by ghost** [taitems/iOS-Overlay#3]

**Comment by taitems** [comment]
I believe it's on the demo page or at the very least mentioned in the blog
post announcing it.

Sent from my iPhone

On 24/01/2013, at 12:57 AM, Hirvesh Munogee notifications@github.com
wrote:

 —
Reply to this email directly or view it on
GitHubhttps://github.com/taitems/iOS-Overlay/issues/3.

**Comment by ghost** [comment]
Pretty sure it's not on the demo page. Could you link me up to the blog post where the license is mentioned?

**Comment by taitems** [comment]
http://taitems.tumblr.com/post/40043132249/iosoverlay-js-ios-overlay-notification-plugin
